services:
  database:
    container_name: ${APP_NAME}-db
    image: yobasystems/alpine-mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${APP_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
networks:
  default:
      name: nginx-proxy
      external: true