version: '3.8'

services:
  php:
    container_name: ${APP_NAME}-php
    build:
      context: ./php
    environment:
      - DATABASE_URL=mysql://${USER_NAME}:${DB_PASSWORD}@${DB_URL}-db:${DB_PORT}/${DB_NAME}
    ports:
      - '9000'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:stable-alpine
    ports:
      - '80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf     
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./logs:/var/log/nginx 
    environment:
        # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - php

networks:
  default:
      name: nginx-proxy
      external: true
